apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosting-deployment
  namespace: microservices
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: hosting-management
          image: bytegenius/hosting_management:v0.4-production
