apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosting-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hosting-app
  template:
    metadata:
      name: hosting-management
      labels:
        app: hosting-app
    spec:
      serviceAccountName: hosting-management
      containers:
        - name: hosting-management
          ports:
            - containerPort: 8000
          env:
            - name: APP_APPLICATION__PORT
              valueFrom:
                configMapKeyRef:
                  name: hosting-configuration
                  key: applicationPort
            - name: APP_APPLICATION__ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: hosting-configuration
                  key: applicationAddress
      imagePullSecrets:
        - name: regcred
