apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base

namespace: microservices

commonLabels:
   infra: hosting

resources:
- deployment.yaml
- service.yaml
- service_account.yaml
- role.yaml
- role_binding.yaml

