apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-role-to-sa
subjects:
  - kind: ServiceAccount
    name: hosting-management
roleRef:
  kind: Role
  name: helm-role
  apiGroup: rbac.authorization.k8s.io
