apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-role
rules:
  - apiGroups: ["", "metrics.k8s.io", "apps"]
    resources:
      - podmetrics
      - pods
      - services
      - deployments
      - secrets
      - replicasets
    verbs:
      - get
      - create
      - delete
      - list
      - update
      - patch

