apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-role-to-sa
  namespace: hosting
subjects:
  - kind: ServiceAccount
    name: hosting-management
    namespace: microservices
roleRef:
  kind: ClusterRole
  name: helm-role
  apiGroup: rbac.authorization.k8s.io
