apiVersion: v1
kind: Service
metadata:
  name: hosting-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: hosting-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30011
